### ISSUE TITLE
Could not remove previous comment

### ISSUE THREAD

**Issue by flyasky** [tomasbjerre/violation-comments-to-gitlab-maven-plugin#3]
Comment was added to gitlab merge request on firs run. But on second run from CI or from console I see error message:

```
INFO: Asking GitLabCommentsProvider to create comment with all single file comments.
Sep 22, 2018 2:32:38 PM se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi$1 log
SEVERE: Could not delete note Comment [content=Found 2 violations:

**Reporter**: Checkstyle

**Rule**: com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck

**Severity**: ERROR

**File**: /..../db/Session.java L93


'=' is not followed by whitespace.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-586920067>*
**Reporter**: Checkstyle

**Rule**: com.puppycrawl.tools.checkstyle.checks.whitespace.MethodParamPadCheck

**Severity**: ERROR

**File**: /..../db/Session.java L94


'(' is preceded with whitespace.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1408038596>*
 *<ACCUMULATED-VIOLATIONS>*, identifier=185962, specifics=[], type=PR]
org.gitlab.api.GitlabAPIException
	at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:432)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:170)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:139)
	at org.gitlab.api.GitlabAPI.deleteNote(GitlabAPI.java:1671)
	at se.bjurr.violations.comments.gitlab.lib.GitLabCommentsProvider.removeComments(GitLabCommentsProvider.java:172)
	at se.bjurr.violations.comments.lib.CommentsCreator.removeOldCommentsThatAreNotStillReported(CommentsCreator.java:152)
	at se.bjurr.violations.comments.lib.CommentsCreator.createCommentWithAllSingleFileComments(CommentsCreator.java:92)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:64)
	at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:39)
	at se.bjurr.violations.comments.gitlab.lib.ViolationCommentsToGitLabApi.toPullRequest(ViolationCommentsToGitLabApi.java:161)
	at se.bjurr.violations.comments.github.maven.ViolationCommentsMojo.execute(ViolationCommentsMojo.java:133)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3607)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:393)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:168)
	... 31 more

```

**Comment by tomasbjerre** [comment]
Can be a permission issue. Does the API Token have permission to delete comments?

**Comment by flyasky** [comment]
I can not see 'delete comments rule'. Only "api" scope.. 

```
Name | Created | Expires | Scopes |  
Private Token | Feb 9, 2018 | Never | api | Revoke
api | Sep 22, 2018 | Never | api | Revoke

And possible scopes:

_Scopes_
**api**
Grants complete read/write access to the API, including all groups and projects.

**read_user**
Grants read-only access to the authenticated user's profile through the /user API endpoint, which includes username, public email, and full name. Also grants access to read-only API endpoints under /users.

**read_repository**
Grants read-only access to repositories on private projects using Git-over-HTTP (not using the API).


```

**Comment by tomasbjerre** [comment]
And the user that has this API token can delete comments from the GUI?

**Comment by flyasky** [comment]
Yes, user can delete comments. Comments seems like from this user.
Hm.. I just see that comments was reported now are deleted. I didn't this via UI. Strange... May be async call?

**Comment by tomasbjerre** [comment]
The plugin does not do any async calls. You are not running the plugin in parallell?

Only thing I can think of is that it tried to delete a comment that was already deleted. And that sounds like it was run twice simultaneously.

**Comment by flyasky** [comment]
>You are not running the plugin in parallell?
No

**Comment by tomasbjerre** [comment]
I can reproduce it also! It is a problem in the rest client: https://github.com/timols/java-gitlab-api/issues/321

**Comment by tomasbjerre** [comment]
I'm releasing 1.24 now with a fix for this.
